# Generated by Django 2.0.1 on 2019-02-19 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='pid',
            new_name='parent',
        ),
    ]
